apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-container
spec:
  params:
    - name: serviceaccount-secret
      description: "Secret to service account that can access the ephemeral namespace"
    - name: SNAPSHOT
      description: The JSON string of the Snapshot under test
    - name: pod-name
  results:
    - name: component-container-image
      description: image url and tag
  steps:
    - name: echo
      image: registry.redhat.io/openshift4/ose-cli:4.13@sha256:73df37794ffff7de1101016c23dc623e4990810390ebdabcbbfa065214352c7c
      env:
        - name: COMPONENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['appstudio.openshift.io/component']
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: SECRETNAME
          value: $(params.serviceaccount-secret)
        - name: PODNAME
          value: $(params.pod-name)
      script: |
        #!/bin/bash
        set -ex
        set -o pipefail

        oc get secret $SECRETNAME --template '{{.data.kubeconfig}}' | base64 -d > /kubeconfig
        export KUBECONFIG=/kubeconfig

        dnf install -y jq gettext
        export COMPONENT_CONTAINER_IMAGE=$(jq -r --arg component_name "${COMPONENT_NAME}" '.components[] | select(.name == $component_name) | .containerImage' <<< "${SNAPSHOT}")
        echo -n "${COMPONENT_CONTAINER_IMAGE}" > $(results.component-container-image.path)

        echo "Echoing component container image"

        curl https://raw.githubusercontent.com/jencull/flask-konflux/main/.tekton/integration/pod-and-svc.yaml | envsubst | oc apply -f -

        CLUSTER_IP=$(oc expose pod $PODNAME -o jsonpath={.spec.clusterIP})

        max_attempts=10  # Number of retry attempts
        attempt=1        # Initial attempt
        backoff_time=10  # Time in seconds between attempts

        while true; do
        echo "Checking if pod $PODNAME is ready (Attempt $attempt/$max_attempts)..."
  
        oc wait --for=condition=Ready pod/$PODNAME --timeout=10s && break
  
        if [[ $attempt -eq $max_attempts ]]; then
          echo "Pod $PODNAME is not ready after $max_attempts attempts. Exiting..."
          exit 1
        fi
  
        attempt=$((attempt + 1))
        sleep $backoff_time
        done

        OUTPUT=$(oc run -i --tty --rm debug --image=curlimages/curl --restart=Never -- curl ${PODNAME}:5000)

        oc run -i --tty --rm debug --image=curlimages/curl --restart=Never -- curl ${PODNAME}:5000
        assert_eq "$OUTPUT" "<h1>Hello from Flask & Dockerfile</h1>"

        if ! assert_eq "$OUTPUT" "<h1>Hello from Flask & Konflux</h1>"; then
          echo "Test failed. Exiting."
          exit 1
        fi    
