apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: hello
  namespace: rh-ee-jcullina-tenant
spec:
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo "Hello, World!"
