apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: export-pipeline-logs
  labels:
    app.kubernetes.io/managed-by: tekton
spec:
  description: |
    Gathers all logs from a completed Tekton PipelineRun, packages them into a simple
    OCI artifact (tar.gz blob) and pushes it to a specified Quay repository.
  params:
    - name: quay-repo
      type: string
      description: The base Quay repository path (e.g., quay.io/org/repo).
    - name: pipeline-run-name
      type: string
      description: The name of the PipelineRun whose logs should be collected.
    - name: namespace
      type: string
      description: The namespace where the PipelineRun was executed.
      default: "$(context.pipelineRun.namespace)"
    - name: artifact-credentials-secret
      type: string
      description: Name of the secret containing registry credentials (must match what secure-push-oci expects, e.g., 'oci-storage-dockerconfigjson' key).
  results:
    - name: LOG_ARTIFACT_TAG
      description: The specific tag generated for the log artifact.
  workspaces:
    - name: shared-data
      description: Workspace for log archiving and image creation files. 
  volumes:
    - name: credentials-volume
      secret:
        secretName: $(params.artifact-credentials-secret)
  steps:
    - name: fetch-and-prepare-logs
      image: registry.redhat.io/openshift4/ose-cli:latest
      workingDir: $(workspaces.shared-data.path)
      env:
        - name: PR_NAME
          value: "$(params.pipeline-run-name)"
        - name: PR_NAMESPACE
          value: "$(params.namespace)"
        - name: HOME
          value: /tmp
      script: |
        #!/bin/bash
        set -euo pipefail

        microdnf install jq -y || {
          echo "Warning: microdnf failed. Attempting dnf install."
          dnf install jq -y
        }
        
        LOG_FILENAME="logs.txt"
        ARCHIVE_FILENAME="logs.tar.gz"
        IMAGE_TAG="$(params.pipeline-run-name)-$(date +%Y%m%d%H%M%S)-logs"

        echo "Starting log export for PipelineRun: ${PR_NAME}"
        
        CMD="oc"
        if ! command -v oc &> /dev/null; then
          CMD="kubectl"
        fi

        set -x 
        
        ${CMD} logs --namespace "${PR_NAMESPACE}" pipelinerun/"${PR_NAME}" --all > "${LOG_FILENAME}" 2>&1 || {
            echo "Primary log retrieval failed, attempting fallback for older clusters by tasks..."
            ${CMD} get pr "${PR_NAME}" -o json -n "${PR_NAMESPACE}" | jq -r '.status.childReferences[].name' | while read taskrun; do
              ${CMD} logs --namespace "${PR_NAMESPACE}" taskrun/"${taskrun}" --all >> "${LOG_FILENAME}" 2>&1 || true
            done
        }

        set +x
        
        if [ -s "${LOG_FILENAME}" ]; then
            echo "Successfully fetched logs."
            tar -czf "${ARCHIVE_FILENAME}" "${LOG_FILENAME}"
            echo "Created compressed archive: ${ARCHIVE_FILENAME}"
            
            # Write the tag to the Tekton result
            echo -n "${IMAGE_TAG}" > $(results.LOG_ARTIFACT_TAG.path)
            # Also write to a file for use in the next step
            echo -n "${IMAGE_TAG}" > image-tag.txt
        else
            echo "Warning: Log file is empty. Skipping artifact creation."
            exit 0
        fi

    - name: push-log-artifact
      image: registry.redhat.io/openshift4/ose-cli:latest
      workingDir: $(workspaces.shared-data.path)
      env:
        - name: HOME
          value: /tmp
        - name: QUAY_REPO
          value: $(params.quay-repo)
      script: |
        #!/bin/bash
        set -euo pipefail
        
        # Read the tag from the file created in the previous step
        IMAGE_TAG=$(cat image-tag.txt)
        OCI_REF="${QUAY_REPO}:${IMAGE_TAG}"
        
        echo "Pushing log artifact to: ${OCI_REF}"
        
        # Install oras if not available
        if ! command -v oras &> /dev/null; then
          echo "Installing oras..."
          ORAS_VERSION="1.1.0"
          curl -LO "https://github.com/oras-project/oras/releases/download/v${ORAS_VERSION}/oras_${ORAS_VERSION}_linux_amd64.tar.gz"
          tar -xzf "oras_${ORAS_VERSION}_linux_amd64.tar.gz" -C /usr/local/bin/ oras
          chmod +x /usr/local/bin/oras
          rm "oras_${ORAS_VERSION}_linux_amd64.tar.gz"
        fi
        
        # Set up authentication
        if command -v select-oci-auth &> /dev/null; then
          select-oci-auth "${QUAY_REPO}" > "$HOME/auth.json" || {
            echo "Failed to select OCI auth"
            exit 1
          }
          export DOCKER_CONFIG="$HOME"
        elif [ -f "/tekton/creds/.docker/config.json" ]; then
          # Fallback to Tekton credentials
          mkdir -p "$HOME/.docker"
          cp /tekton/creds/.docker/config.json "$HOME/.docker/config.json" || true
          export DOCKER_CONFIG="$HOME/.docker"
        else
          echo "No authentication method found"
          exit 1
        fi
        
        #  Push the tar.gz file as an OCI artifact
        oras push --no-tty \
          --artifact-type "application/vnd.logs.tar+gzip" \
          "${OCI_REF}" \
          "logs.tar.gz:application/vnd.logs.tar+gzip" || {
          echo "Failed to push artifact"
          exit 1
        }
        
        echo "Successfully pushed log artifact to ${OCI_REF}"
      volumeMounts:
        - name: credentials-volume
          mountPath: /tekton/creds
