apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: export-pipeline-logs
  labels:
    app.kubernetes.io/managed-by: tekton
spec:
  # ... (params, results, workspaces, volumes are unchanged) ...
  steps:
    - name: fetch-and-prepare-logs
      image: registry.redhat.io/openshift4/ose-cli:latest
      workingDir: $(workspaces.shared-data.path)
      env:
        - name: PR_NAME
          value: "$(params.pipeline-run-name)"
        - name: PR_NAMESPACE
          value: "$(params.namespace)"
        - name: OCI_REPO_WITH_TAG
          value: "$(params.quay-repo)"
        - name: HOME
          value: /tmp
      script: |
        #!/bin/bash
        set -euo pipefail
        microdnf install jq -y || dnf install jq -y
        
        LOG_FILENAME="all-logs.txt"
        ARCHIVE_FILENAME="logs.tar.gz"
        
        REPO_NAME_ONLY="${OCI_REPO_WITH_TAG%:*}"
        IMAGE_TAG="${PR_NAME}-$(date +%Y%m%d%H%M%S)-logs"
        FULL_OCI_REF="${REPO_NAME_ONLY}:${IMAGE_TAG}"

        CMD="oc"
        if ! command -v oc &> /dev/null; then
          CMD="kubectl"
        fi

        set -x 
        
        ${CMD} logs --namespace "${PR_NAMESPACE}" pipelinerun/"${PR_NAME}" --all > "${LOG_FILENAME}" 2>&1 || {
            echo "Primary log retrieval failed, attempting fallback for older clusters by tasks..."
            ${CMD} get pr "${PR_NAME}" -o json -n "${PR_NAMESPACE}" | jq -r '.status.childReferences[].name' | while read taskrun; do
              ${CMD} logs --namespace "${PR_NAMESPACE}" taskrun/"${taskrun}" --all >> "${LOG_FILENAME}" 2>&1 || true
            done
        }

        set +x
        
        if [ -s "${LOG_FILENAME}" ]; then
            echo "Successfully fetched logs."
            tar -czf "${ARCHIVE_FILENAME}" "${LOG_FILENAME}"
            echo "Created compressed archive: ${ARCHIVE_FILENAME}"
            
            echo -n "${IMAGE_TAG}" > $(results.LOG_ARTIFACT_TAG.path)
            echo -n "${FULL_OCI_REF}" > $(results.OCI_REFERENCE.path) 
            echo "Generated OCI reference: ${FULL_OCI_REF}"
        else
            echo "Warning: Log file is empty. Skipping artifact creation."
            exit 0
        fi

    - name: push-log-artifact
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/tekton-integration-catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/secure-push-oci/0.1/secure-push-oci.yaml
      params:
        - name: workdir-path
          value: $(workspaces.shared-data.path)
        - name: oci-ref
          value: $(steps.fetch-and-prepare-logs.results.OCI_REFERENCE)
        - name: credentials-volume-name
          value: credentials-volume
        # ⬅️ FIX: Re-adding the necessary parameters for the StepAction
        - name: file-path
          value: logs.tar.gz
        - name: media-type
          value: application/vnd.logs.tar+gzip
      volumeMounts:
        - name: credentials-volume
          mountPath: /tekton/creds/.docker # Mount the volume's contents into this directory
          readOnly: true
