apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: export-pipeline-logs
  labels:
    app.kubernetes.io/managed-by: tekton
spec:
  description: |
    Gathers all logs from a completed Tekton PipelineRun, packages them into a simple
    OCI artifact (tar.gz blob), and pushes it to a specified Quay repository using direct
    OCI push commands.
  params:
    - name: quay-repo
      type: string
      description: The base OCI repository path (e.g., quay.io/org/repo).
    - name: pipeline-run-name
      type: string
      description: The name of the PipelineRun whose logs should be collected.
    - name: namespace
      type: string
      description: The namespace where the PipelineRun was executed.
      default: "$(context.pipelineRun.namespace)"
    - name: artifact-credentials-secret
      type: string
      description: Name of the secret containing registry credentials.
  results:
    - name: LOG_ARTIFACT_TAG
      description: The specific tag generated for the log artifact.
  workspaces:
    - name: shared-data
      description: Workspace for log archiving and OCI artifact creation files. 
  volumes:
    - name: credentials-volume
      secret:
        secretName: $(params.artifact-credentials-secret)
  steps:
    - name: fetch-and-prepare-logs
      image: quay.io/konflux-ci/tekton-integration-catalog/utils:latest
      workingDir: $(workspaces.shared-data.path)
      env:
        - name: PR_NAME
          value: "$(params.pipeline-run-name)"
        - name: PR_NAMESPACE
          value: "$(params.namespace)"
        - name: OCI_REPO_WITH_TAG
          value: "$(params.quay-repo)"
      script: |
        #!/bin/bash
        set -euo pipefail
        
        LOG_FILENAME="all-logs.txt"
        ARCHIVE_FILENAME="logs.tar.gz"
        
        REPO_NAME_ONLY="${OCI_REPO_WITH_TAG%:*}"
        IMAGE_TAG="${PR_NAME}-$(date +%Y%m%d%H%M%S)-logs"
        
        CMD="kubectl"
        
        # 1. Fetch logs by TaskRun and get the Pod name (to bypass client schema errors)
        ${CMD} get pr "${PR_NAME}" -o json -n "${PR_NAMESPACE}" | jq -r '.status.childReferences[].name' | while read taskrun; do
            POD_NAME=$(${CMD} get tr "${taskrun}" -o json -n "${PR_NAMESPACE}" | jq -r '.status.podName // empty')

            if [ -n "$POD_NAME" ]; then
                echo "--- LOGS FOR ${taskrun} (Pod: ${POD_NAME}) ---" >> "${LOG_FILENAME}" 2>&1
                ${CMD} logs --namespace "${PR_NAMESPACE}" pod/"${POD_NAME}" >> "${LOG_FILENAME}" 2>&1 || true
            fi
        done
        
        # 2. Archive and set result if logs exist
        if [ -s "${LOG_FILENAME}" ]; then
            tar -czf "${ARCHIVE_FILENAME}" "${LOG_FILENAME}"
            echo -n "${IMAGE_TAG}" > $(results.LOG_ARTIFACT_TAG.path)
        else
            exit 0
        fi

    - name: secure-push-oci-direct
      image: quay.io/konflux-ci/tekton-integration-catalog/utils:latest
      workingDir: $(workspaces.shared-data.path)
      env:
        - name: OCI_REFERENCE_BASE
          value: $(params.quay-repo)
      script: |
        #!/bin/bash
        set -euo pipefail
        
        IMAGE_TAG=$(cat $(results.LOG_ARTIFACT_TAG.path))
        
        IMAGE_TAG="${PR_NAME}-$(date +%Y%m%d%H%M%S)-logs"
        
        # Setup authentication
        AUTH_DIR="/tekton/volumes/credentials-volume"
        AUTH_PATH="$AUTH_DIR/.dockerconfigjson"
        
        if [ -f "$AUTH_PATH" ]; then
          TEMP_DOCKER_CONFIG="$(mktemp -d)"
          cp "$AUTH_PATH" "$TEMP_DOCKER_CONFIG/config.json"
          export DOCKER_CONFIG="$TEMP_DOCKER_CONFIG"
        fi
        
        # Execute push
        oras push --no-tty \
          --artifact-type "application/vnd.logs.tar+gzip" \
          "${FULL_OCI_REF}" \
          "logs.tar.gz:application/vnd.logs.tar+gzip"
        
        echo "Successfully pushed log artifact to ${FULL_OCI_REF}"
