apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: export-pipeline-logs
  labels:
    app.kubernetes.io/managed-by: tekton
spec:
  description: |
    Gathers all logs from a completed Tekton PipelineRun, packages them into a simple
    "FROM scratch" image artifact, and pushes the image to a specified Quay repository.
  params:
    - name: quay-repo
      type: string
      description: The full path to the Quay repository
    - name: pipeline-run-name
      type: string
      description: The name of the PipelineRun whose logs should be collected.
    - name: namespace
      type: string
      description: The namespace where the PipelineRun was executed.
      default: "$(context.pipelineRun.namespace)"
    - name: registry-credentials-secret
      type: string
      description: Name of the Secret containing the registry credentials for pushing to Quay.
  workspaces:
    - name: shared-data
      description: Workspace for log archiving and image creation files. 
  steps:
    - name: fetch-and-prepare-logs
      image: registry.redhat.io/openshift4/ose-cli:latest
      workingDir: $(workspaces.shared-data.path)
      env:
        - name: PR_NAME
          value: "$(params.pipeline-run-name)"
        - name: PR_NAMESPACE
          value: "$(params.namespace)"
        - name: HOME
          value: /tmp
      script: |
        #!/bin/bash
        set -euo pipefail

        microdnf install jq -y || {
          echo "Warning: microdnf failed. Attempting dnf install."
          dnf install jq -y
        }
        
        LOG_FILENAME="${PR_NAME}-all-logs.txt"
        ARCHIVE_FILENAME="logs.tar.gz"
        IMAGE_TAG="${PR_NAME}-$(date +%Y%m%d%H%M%S)-logs"

        echo "Starting log export for PipelineRun: ${PR_NAME}"
        
        CMD="oc"
        if ! command -v oc &> /dev/null; then
          CMD="kubectl"
        fi

        # Start tracing commands
        set -x 
        
        # Attempt to get all logs from the PipelineRun (standard in modern Tekton)
        ${CMD} logs --namespace "${PR_NAMESPACE}" pipelinerun/"${PR_NAME}" --all > "${LOG_FILENAME}" 2>&1 || {
            echo "Primary log retrieval failed, attempting fallback for older clusters by tasks..."
            # Fallback for older clusters
            ${CMD} get pr "${PR_NAME}" -o json -n "${PR_NAMESPACE}" | jq -r '.status.childReferences[].name' | while read taskrun; do
              ${CMD} logs --namespace "${PR_NAMESPACE}" taskrun/"${taskrun}" --all >> "${LOG_FILENAME}" 2>&1 || true
            done
        }

        # Stop tracing commands
        set +x
        
        if [ -s "${LOG_FILENAME}" ]; then
            echo "Successfully fetched logs."
            tar -czf "${ARCHIVE_FILENAME}" "${LOG_FILENAME}"
            echo "Created compressed archive: ${ARCHIVE_FILENAME}"
            
            echo "FROM scratch" > Dockerfile
            echo "LABEL konflux-log-archive-name=\"${IMAGE_TAG}\"" >> Dockerfile
            echo "COPY ${ARCHIVE_FILENAME} /" >> Dockerfile
            echo "Created Dockerfile for log artifact"

            echo -n "${IMAGE_TAG}" > $(workspaces.shared-data.path)/IMAGE_TAG
        else
            echo "Warning: Log file is empty. Skipping artifact creation."
            exit 0
        fi

    - name: build-and-push-to-quay
      image: 'quay.io/buildah/stable:latest'
      workingDir: $(workspaces.shared-data.path)
      env:
        - name: QUAY_REPO
          value: $(params.quay-repo)
      script: |
        #!/bin/bash
        set -euo pipefail

        IMAGE_TAG=$(cat $(workspaces.shared-data.path)/IMAGE_TAG 2>/dev/null || echo "")
        
        if [ -z "${IMAGE_TAG}" ]; then
            echo "Skipping push step, log archive not found."
            exit 0
        fi

        FULL_IMAGE_URL="${QUAY_REPO}:${IMAGE_TAG}"

        echo "Building log artifact image..."

        # The debug check is removed since we trust the SA now.

        podman build -t "${FULL_IMAGE_URL}" -f Dockerfile .

        echo "Pushing log artifact to Quay: ${FULL_IMAGE_URL}"
        podman push "${FULL_IMAGE_URL}"
        
        echo "Log artifact successfully uploaded to Quay"
