apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: export-pipeline-logs
  labels:
    app.kubernetes.io/managed-by: tekton
spec:
  description: |
    Gathers all logs from a completed Tekton PipelineRun, packages them into a simple
    OCI artifact (tar.gz blob), constructs the final OCI reference, and pushes it to 
    a specified Quay repository using a secure OCI push step.
  params:
    - name: quay-repo
      type: string
      description: The base OCI repository path (e.g., quay.io/org/repo).
    - name: pipeline-run-name
      type: string
      description: The name of the PipelineRun whose logs should be collected.
    - name: namespace
      type: string
      description: The namespace where the PipelineRun was executed.
      default: "$(context.pipelineRun.namespace)"
    - name: artifact-credentials-secret
      type: string
      description: Name of the secret containing registry credentials.
  results:
    - name: LOG_ARTIFACT_TAG
      description: The specific tag generated for the log artifact.
    - name: OCI_REFERENCE
      description: The final fully constructed OCI reference (repo:tag).
  workspaces:
    - name: shared-data
      description: Workspace for log archiving and OCI artifact creation files. 
  volumes:
    - name: credentials-volume
      secret:
        secretName: $(params.artifact-credentials-secret)
  steps:
    - name: fetch-and-prepare-logs
      image: registry.redhat.io/openshift4/ose-cli:latest
      workingDir: $(workspaces.shared-data.path)
      env:
        - name: PR_NAME
          value: "$(params.pipeline-run-name)"
        - name: PR_NAMESPACE
          value: "$(params.namespace)"
        - name: OCI_REPO_WITH_TAG
          value: "$(params.quay-repo)"
        - name: HOME
          value: /tmp
      script: |
        #!/bin/bash
        set -euo pipefail

        # Install jq if needed
        microdnf install jq -y || dnf install jq -y
        
        LOG_FILENAME="all-logs.txt"
        ARCHIVE_FILENAME="logs.tar.gz"
        
        # 1. Strip the existing tag/revision from the base OCI_REPO_WITH_TAG string.
        # This keeps only the repository name (quay.io/org/repo/component), 
        # allowing us to append the new tag safely.
        REPO_NAME_ONLY="${OCI_REPO_WITH_TAG%:*}"
        
        # Generate unique timestamp tag
        IMAGE_TAG="${PR_NAME}-$(date +%Y%m%d%H%M%S)-logs"
        
        # 2. Construct the corrected full OCI reference: repo:new-log-tag
        FULL_OCI_REF="${REPO_NAME_ONLY}:${IMAGE_TAG}"

        echo "Starting log export for PipelineRun: ${PR_NAME}"
        
        CMD="oc"
        if ! command -v oc &> /dev/null; then
          CMD="kubectl"
        fi

        set -x 
        
        # Log retrieval logic: Attempt to get all logs from the PipelineRun, 
        # falling back to getting logs per TaskRun if the primary command fails.
        ${CMD} logs --namespace "${PR_NAMESPACE}" pipelinerun/"${PR_NAME}" --all > "${LOG_FILENAME}" 2>&1 || {
            echo "Primary log retrieval failed, attempting fallback for older clusters by tasks..."
            ${CMD} get pr "${PR_NAME}" -o json -n "${PR_NAMESPACE}" | jq -r '.status.childReferences[].name' | while read taskrun; do
              # We use '|| true' here to ensure the loop continues even if a specific taskrun log fails
              ${CMD} logs --namespace "${PR_NAMESPACE}" taskrun/"${taskrun}" --all >> "${LOG_FILENAME}" 2>&1 || true
            done
        }

        set +x
        
        if [ -s "${LOG_FILENAME}" ]; then
            echo "Successfully fetched logs."
            tar -czf "${ARCHIVE_FILENAME}" "${LOG_FILENAME}"
            echo "Created compressed archive: ${ARCHIVE_FILENAME}"
            
            # Write the tag to the dedicated Task Result
            echo -n "${IMAGE_TAG}" > $(results.LOG_ARTIFACT_TAG.path)
            
            # Write the FULL OCI reference to the new Result for the next step to consume
            echo -n "${FULL_OCI_REF}" > $(results.OCI_REFERENCE.path) 
            echo "Generated OCI reference: ${FULL_OCI_REF}"
        else
            echo "Warning: Log file is empty. Skipping artifact creation."
            exit 0
        fi

    - name: push-log-artifact
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/tekton-integration-catalog.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/secure-push-oci/0.1/secure-push-oci.yaml
      params:
        - name: workdir-path
          value: $(workspaces.shared-data.path)
        # FIX: Passes the corrected URL from the Task Result
        - name: oci-ref
          value: $(steps.fetch-and-prepare-logs.results.OCI_REFERENCE)
        - name: credentials-volume-name
          value: credentials-volume
